I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 526, in script
    Katy "Ой, кажется, я вам забыла об этом сказать..."
Exception: Sayer 'Katy' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 526, in script
    Katy "Ой, кажется, я вам забыла об этом сказать..."
  File "E:\Program Files Portable\renpy-8.1.0-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "E:\Program Files Portable\renpy-8.1.0-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Katy' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Дебург: история Мэри 1.3
Sun Mar 24 17:19:41 2024
